# Generated by Django 4.1 on 2022-08-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_add_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='add_friend_request',
            field=models.ManyToManyField(to='hello.profile'),
        ),
        migrations.DeleteModel(
            name='Add_friend_request',
        ),
    ]
