# Generated by Django 4.1 on 2022-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_message_chat_profile_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
